version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-emkademy}"
    image: emkonfig
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-kyuksel}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
    container_name: emkonfig-container
    ipc: host
    init: true
