backbone: resnet50

_{some_class as model}:
  some_arg: 64
  backbone: ${backbone}

data_module:
  batch_size: 32
  n_workers: 8
  _{some_class as dataset}:
    lala: 32
    hoho: nihaha

training_task:
  data_module: ${data_module}

  lightning_module:
    _target_: dummy.lightning_modules.SomeLightningModule
    model: ${model}

evaluation_task:
  data_module: ${data_module}

  lightning_module:
    model: ${model}
    batch_size: ${data_module.batch_size}
    oldu: ${./configs/backbones/resnet50.yaml}

head: ${./configs/heads/linear.yaml}

asd:
  bsd: ${data_module.dataset}
