defaults:
  - head@this_is_from_defaults_list: linear
  - callback/stack@callbacks:
      - callback1
      - callback2
      - callback3

backbone: resnet50

_{some_class as model}:
  some_arg: 64
  backbone: ${backbone}

data_module:
  batch_size: 32
  n_workers: 8
  _{some_class as dataset}:
    lala: 32
    lorem: ipsum

training_task:
  data_module: ${data_module}
  some_param:
    - _{some_class as some_class_renamed}:
        param1: param1
        random1: random1
        backbone: ${backbone}
    - ${training_task.some_param[0].some_class_renamed.random1}

  lightning_module:
    _target_: dummy.lightning_modules.SomeLightningModule
    model: ${model}

evaluation_task:
  data_module: ${data_module}

  lightning_module:
    model: ${model}
    batch_size: ${data_module.batch_size}
    resnet50_reference: ${./examples/configs/backbone/resnet50.yaml}

head: ${./examples/configs/head/linear.yaml}

asd:
  bsd: ${data_module.dataset}

_{yet_another_class as yet_another_class_renamed}:
  fox: 5
  _{some_other_class}:
    batch_size: 1212

datamodule:
  _{some_other_class as _}:
    batch_size: 1212

_{lala}: null

lala:
  bsd: 5

head:
  thusubasa: sahin_vurusu
